VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Class1"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Sub Macro1()
'
' Macro1 Macro
' visual basic atm program .sten object by system .event )hand
' "&chr(10)&"public class transaction box
' "&chr(10)&"const service as decimal =6.5
' "&chr(10)&"const pin as integer +9343
' "&chr(10)&"dim balance as decimal =150
' "&chr(10)&"private sub label 12_click (by sender System.object event arg handles labe
'
End Sub
Sub Macro2()
'
' Macro2 Macro
' type meter three phase ac static watt hous smart
' "&chr(10)&"metering algorith
' "&chr(10)&"accuracy  nomial voltage  mettering frequence metering const functionality current sensors energy pulse energy temper detection remote communication iec 62056 extrevm internal battery
'
    ActiveWindow.ActivePane.VerticalPercentScrolled = 205
    ActiveWindow.ActivePane.VerticalPercentScrolled = 146
    Selection.TypeText Text:= _
        "------------------------------------------------------------"
    Selection.TypeText Text:= _
        "------------------------------------------------------------"
    Selection.TypeText Text:="-------"
    Selection.TypeParagraph
    Selection.PasteAndFormat (wdFormatOriginalFormatting)
    ActiveWindow.ActivePane.VerticalPercentScrolled = 146
    Selection.TypeParagraph
    Selection.TypeParagraph
    Selection.TypeParagraph
    Selection.TypeParagraph
    Selection.TypeParagraph
    Selection.TypeParagraph
    Selection.TypeParagraph
    Selection.TypeParagraph
    Selection.TypeParagraph
    Selection.TypeParagraph
    Selection.TypeParagraph
    Selection.TypeParagraph
    Selection.TypeParagraph
    Selection.TypeParagraph
    Selection.TypeParagraph
    Selection.TypeParagraph
    Selection.TypeParagraph
    Selection.TypeParagraph
    Selection.TypeParagraph
    Selection.TypeParagraph
    Selection.TypeParagraph
    Selection.TypeParagraph
    Selection.TypeParagraph
    Selection.TypeParagraph
    Selection.TypeParagraph
    Selection.Paste
    ActiveDocument.Save
    ActiveWindow.ActivePane.VerticalPercentScrolled = 207
    ActiveWindow.ActivePane.VerticalPercentScrolled = 202
    ActiveWindow.ActivePane.VerticalPercentScrolled = 197
    ActiveWindow.ActivePane.LargeScroll Down:=1
    ActiveWindow.ActivePane.VerticalPercentScrolled = -75
    ActiveWindow.ActivePane.VerticalPercentScrolled = -41
    Windows("Doc8 drawing tshingombe fiston").Activate
    Windows("Doc2 drawing tshingombe").Activate
    ActiveWindow.ActivePane.VerticalPercentScrolled = 127
    ActiveWindow.Close
    ActiveWindow.Close
    ActiveWindow.Close
    ActiveWindow.Close
    ActiveWindow.Close
    ChangeFileOpenDirectory "C:\Users\Library SIX\Desktop\"
    ActiveDocument.SaveAs2 FileName:="Doc1 tshing.docx", FileFormat:= _
        wdFormatXMLDocument, LockComments:=False, Password:="", AddToRecentFiles _
        :=True, WritePassword:="", ReadOnlyRecommended:=False, EmbedTrueTypeFonts _
        :=False, SaveNativePictureFormat:=False, SaveFormsData:=False, _
        SaveAsAOCELetter:=False, CompatibilityMode:=15
    ActiveWindow.Close
    Application.Quit
End Sub
Sub Macro3()
'
' Macro3 Macro
' 170.{ “ IF (X1=0)+(X2=0)+(X3=0)+(X4=0)+(X5=0)+(X6=0)+(X7=0)+(X8=)THEN ”}  OR “SUB”_” CLICK”
' "&chr(10)&" “SELECT REGISTER .ELSE , CPU”=0 ,  ADRESSPIN = 000000000
' "&chr(10)&"180 END IF “ IF (S1=0)+(S2=0)+(S3=0)+(S4=0)+(S5=0)+(S6=0)+(S7=0)+(S8=0)THEN ”}  OR “SUB”_” CLICK
' "&chr(10)&"EXECU
'
    Application.Run MacroName:="frm1"
End Sub
Sub Macro4()
'
' Macro4 Macro
' 170.{ “ IF (X1=0)+(X2=0)+(X3=0)+(X4=0)+(X5=0)+(X6=0)+(X7=0)+(X8=0)THEN ”}  OR “SUB”_” CLICK”
' "&chr(10)&" SELECT REGISTER .ELSE , CPU ,
' "&chr(10)&"180 END IF “ IF (S1=1)+(S2=1)+(S3=1)+(S4=1)+(S5=1)+(S6=1)+(S7=1)+(S8=1)THEN ”}  OR “SUB”_” CLICK
' "&chr(10)&"EXECUTION LOOP
'

'
    Application.Run MacroName:="frm1"
    ActiveWindow.ActivePane.VerticalPercentScrolled = 119
    Selection.Copy
    Application.Run MacroName:="frm1"
End Sub
Sub Macro5()
'
' Macro5 Macro
' 10.INPUT X1
' "&chr(10)&"20. INPUT .X2
' "&chr(10)&"30. INPUT X3
' "&chr(10)&"40. INPUT X4
' "&chr(10)&"50,IN[UT X5
' "&chr(10)&"60. INPUT X6
' "&chr(10)&"60.INPUT .X7.
'

' "&chr(10)&" 70.OUTPUT  S1
' "&chr(10)&"80.OUTPUT.S2
' "&chr(10)&"90,OUTPUT S3
' "&chr(10)&"100.OUTPUT S4
' "&chr(10)&"110.OUTPUT S5
' "&chr(10)&"120 OUTPUT S6
' "&chr(10)&"130.OUTPUT S7
' "&chr(10)&"140.OUTPUT
' "&chr(10)&"150 SELECT REGISTER
' "&chr(10)&"150 OUTPUT HARDW
'
    Application.Run MacroName:="frm1"
End Sub
Sub frm1()
'
' frm1 Macro
'
'

End Sub
Sub Macro24()
'
' Macro24 Macro
'
' "&chr(10)&"   \(f(x,y)\) the partial derivatives with respect to \(x\)
' "&chr(10)&"
' "&chr(10)&"   Is denoted as \(\ frac{\ partial f }{ partial x}\) and with ,
' "&chr(10)&"
' "&chr(10)&"   Respect to \ ( y\) as \(\ frac {\ partial f }{\ partial ,y }\) 
' "&chr(10)&"
' "&chr(10)&"   Examp : \[ funct \[ f( x,y)=x^2y+3xy^3\]
' "&chr(10)&"
' "&chr(10)&"   * Calcu
'
End Sub
Sub Macro6()
'
' Macro6 Macro
'
' "&chr(10)&"   \(f(x,y)\) the partial derivatives with respect to \(x\)
' "&chr(10)&"
' "&chr(10)&"   Is denoted as \(\ frac{\ partial f }{ partial x}\) and with ,
' "&chr(10)&"
' "&chr(10)&"   Respect to \ ( y\) as \(\ frac {\ partial f }{\ partial ,y }\) 
' "&chr(10)&"
' "&chr(10)&"   Examp : \[ funct \[ f( x,y)=x^2y+3xy^3\]
' "&chr(10)&"
' "&chr(10)&"   * Calcu
'
End Sub
Sub Macro7()
'
' Macro7 Macro
'
' "&chr(10)&"   \( f(x,y)\), the total derivatives \ ( DF \) is given by : \[ DF = \ frac { \ partial f }{\ partial x }sx +\ frac{ \ partial }{ \ partial y } St \ ]
' "&chr(10)&"
' "&chr(10)&"   Using the previous : \ [ DF = 2xy+ 2y^2)
' "&chr(10)&"
'

'
End Sub
Sub Macro8()
'
' Macro8 Macro
'   1. Fourier series : the Fourier series and cosine function for periodic function \ ( ft)\) with period ( t) the Fourier series is.
' "&chr(10)&"
' "&chr(10)&"   f(t)= a 0+\ sum ${n= 1}{\ infty}
' "&chr(10)&"
' "&chr(10)&"   \ left + a_ n \ cos \ left \ left + } frac { 2\ pi not }{T}
' "&chr(10)&"
' "&chr(10)&"   \ right ) + b _
'
End Sub
Sub Macro9()
'
' Macro9 Macro
'
' "&chr(10)&"   .\[ R-{\ text t{ total }}= R1+R2+R3\]
' "&chr(10)&"
' "&chr(10)&"   . Substituting the values \[ R - { \ text { total }}= 10\.\ text , { ohms }+ 20\, text{ ohms}+30\, text {ohms}\], calculating ,\[ R - { \ text { total /}} = 60\\ text { ohm }\]
'

'
End Sub
Sub Macro10()
'
' Macro10 Macro
' 0
' "&chr(10)&"   [ Z =\ sqrt{R^ 2+(x-L-X_C)^2}\]
' "&chr(10)&"
' "&chr(10)&"   Where _\(x_L= 2\ pi f L \ Pi .f.c\} ( capacitive reactance , 
' "&chr(10)&"
' "&chr(10)&"   -\(X_C)=\ frac ,{1}{2\ pi.f.c}\}( capacitive reactance.
' "&chr(10)&"
' "&chr(10)&"   -|(fI) is the frequency in Hertz ( z)
' "&chr(10)&"
' "&chr(10)&"   -\(L/) is the inductance  in Hertz ( Hz )
'
End Sub
Sub Macro11()
'
' Macro11 Macro
'   The power factor ,of is defined as the ratio of real power to apparent power , \ [ \ text power factor ,of )}=\ frac ,{P}{s}\]
' "&chr(10)&"
' "&chr(10)&"   Where : .\(P\)= real power ( w)
' "&chr(10)&"
' "&chr(10)&"   .\(S\\)= apparent power ,( VA)
'

'
End Sub
Sub Macro12()
'
' Macro12 Macro
'   \[S=\sqt{P^2+Q^2}\]
' "&chr(10)&"
' "&chr(10)&"   .value .real power (\(P\))=500w,
' "&chr(10)&"
' "&chr(10)&"   .reactive power(\Q\))=300VAR
' "&chr(10)&"
' "&chr(10)&"   - calculate apparent power ( s)\[,S=\sqt{P^2t
'

'
End Sub
Sub Macro13()
'
' Macro13 Macro
'
' "&chr(10)&"   -where .
' "&chr(10)&"
' "&chr(10)&"   |(a-O=| frac {1}{T} int- 0^ f(t)\dt)
' "&chr(10)&"
' "&chr(10)&"   .\+a-n = frac {2}{T} int_O^Y f ( t) \ cos\ left ( \ frac { 2\ Pi .n t}{ t } rigth \, DT have simple square wave function.
'

'
End Sub
Sub Macro14()
'
' Macro14 Macro
'   - the Fourier transform is used to convert a time domain signal into it frequency domain represent formula : transform \ F ( \ omega )\( of a continuous signal \ ( f(t) , e^{- j \ omega }\ dt\]
' "&chr(10)&"
' "&chr(10)&"   - where . \( f+ \ omega )\) = Fourier transform of the
'
End Sub
Sub Macro15()
'
' Macro15 Macro
'   - the la place trans is another transformation used to analyse linear time _ invariant system formula for the la place transform \ F( S)\) of function \ ( f(t)\) is \[f(s)=\ into -{O} infty } ,  f( t ) ,, e{-st } St \]
' "&chr(10)&"
' "&chr(10)&"   - \( f( s)\)= Laplace transfor
'
End Sub
Sub Macro16()
'
' Macro16 Macro
'   \|[ | dot { x}(t}=Ax(t)+By(t)\]\[y(t)=(x(t)+du(t)\]
' "&chr(10)&"
' "&chr(10)&"   Where :
' "&chr(10)&"
' "&chr(10)&"   -|(x(t)\)= state vector 
' "&chr(10)&"
' "&chr(10)&"   .|(u(t)\)= Input vector 
' "&chr(10)&"
' "&chr(10)&"   .\ (y( t) \)= output vector .
' "&chr(10)&"
' "&chr(10)&"   .(A\)= System .
' "&chr(10)&"
' "&chr(10)&"   .\(B\)= input matrix .
' "&chr(10)&"
' "&chr(10)&"   .|(C\) = Output matrix .
' "&chr(10)&"
' "&chr(10)&"   .\( D \ )
'
End Sub
Sub Macro17()
'
' Macro17 Macro
'   1. DC machines : speed ( n ) the speed of DC motor can be calculated using formula \[N=\ frac { V-1\ CDOT -R}{ CDOT \ Phi }\]
' "&chr(10)&"
' "&chr(10)&"   - where \ ( N\ ) = speed in Rpm ( revolution perminute .
' "&chr(10)&"
' "&chr(10)&"   - \ ( N\)= supply voltage ( v ) , 
' "&chr(10)&"
' "&chr(10)&"   -\(i\)= armature curr
'
End Sub
Sub Macro18()
'
' Macro18 Macro
'   14*. Mass balance equation : the general mass balance equation can expressed as :
' "&chr(10)&"
' "&chr(10)&"   \[\ text { input }-\ text { output }+\ { generation } \ text  consumption}=\ text { accumulation \ ]
' "&chr(10)&"
'

'
End Sub
Sub Macro19()
'
' Macro19 Macro
'   - for a steady state process ( where accumulation is zero the equation simplified to \[\ text { input}\ text { output}\tezt Generation}-\ text { consumption}=\]
'

'
End Sub
Sub Macro20()
'
' Macro20 Macro
'   - for a steady state process ( where accumulation is zero the equation simplified to \[\ text { input}\ text { output}\tezt Generation}-\ text { consumption}=\]
'

'
End Sub
Sub Macro21()
'
' Macro21 Macro
' 14.1. master  derivatives : electrical derivatives for a simple electrical circuit with an induction ,\(L\) and  a resistor \( R\/ the  voltage across the inductance can be by : \ [ V-L { L\ frac {Di}{St}\]
'

' "&chr(10)&"Where \( v-L)= voltage accross the inductor.
'
End Sub
Sub Macro22()
'
' Macro22 Macro
'   Eingenvalue  analysis for a system represented by a matrix the eingenvalue can indicate stability ,if all aigenvalue have negative real part  the involved finding a lyapunov ,( function \(V(x)\) , such that \(V(X)>0\) and ,,\(\dot{(V)(X)<O\) for stabilit
'
End Sub
Sub Macro23()
'
' Macro23 Macro
'   - r esponse request get ,( f" http:// API electricity meter comparable ,/ { meter _ I'd  "} return response .jsob ( )
'

'
End Sub
Sub Macro25()
'
' Macro25 Macro
'   _1 force balance the net force acting on the system,express as \F-{\text { net }}=F-{\ text { pneumatic}}++ ,
' "&chr(10)&"
' "&chr(10)&"   F-{\text { hydraulic }}- , F {\ text { damping }}-F{\ text ( inertial }}
'

'
End Sub
Sub Macro26()
'
' Macro26 Macro
'   To derive the relationship force ,motion. ,power ,energy .
' "&chr(10)&"
' "&chr(10)&"   \[F= m\ CDOT a \ ] where.
' "&chr(10)&"
' "&chr(10)&"   .\(F\) = force ( N) , | \ ( m \)= mass ( kg ) |\(a)= acceleration ,( m/s.s)
'

'
End Sub
Sub Macro27()
'
' Macro27 Macro
'   Kinetic energy ,( k.E) is the energy of an object du it's motion .
' "&chr(10)&"
' "&chr(10)&"   \[K.E= \frac {I}{2}.m.V^2\..
' "&chr(10)&"
'

'
End Sub
Sub Macro28()
'
' Macro28 Macro
'   Example: Grades: [70,75,80,85,90][70, 75, 80, 85, 90], N=5N = 5:
' "&chr(10)&"   1. Mean:
' "&chr(10)&"
' "&chr(10)&"   µ=70+75+80+85+905=80.\mu = \frac{70 + 75 + 80 + 85 + 90}{5} = 80.
' "&chr(10)&"   2. Variance:
' "&chr(10)&"
' "&chr(10)&"   s2=(70-80)2+(75-80)2+(80-80)2+(85-80)2+(90-80)25=50.\sigma^2 = \frac{(70-80)^2 + (75-80
'
End Sub
Sub Macro29()
'
' Macro29 Macro
' a) Energy in Capacitors
'

' "&chr(10)&"Formula: $$ E = \frac{1}{2} C V^2 $$ Where:
' "&chr(10)&"· CC: Capacitance (Farads),
' "&chr(10)&"· VV: Voltage (Volts).
'

' "&chr(10)&"Example: For a 10 µF10 \, \mu F capacitor with V=240VV = 240V: $$ E = \frac{1}{2} \times 10 \times 10^{-6} \times 240^2 = 0.288
'
End Sub
Sub Macro30()
'
' Macro30 Macro
'
' "&chr(10)&"   B=?0Tc(t) dt,B = \int_0^T c(t) \, dt,
' "&chr(10)&"
' "&chr(10)&"   where c(t)c(t): cost rate over time tt.
' "&chr(10)&"
' "&chr(10)&"   Example: For c(t)=200-20tc(t) = 200 - 20t over [0,5][0, 5]:
' "&chr(10)&"   1. Compute:
' "&chr(10)&"
' "&chr(10)&"   \[ B = \int_0^5 (200 - 20t) \, dt = \left[200t - 10t2\right]_05. \]
' "&chr(10)&"   2. Result:
' "&chr(10)&"
'
End Sub
Sub Macro31()
'
' Macro31 Macro
'   For time-dependent power P(t)P(t), energy is: $$ E = \int_{t_1}^{t_2} P(t) \, dt $$. If P(t)=100sin?(2pt)P(t) = 100 \sin(2\pi t), calculate energy over t=0t = 0 to t=1st = 1s: $$ E = \int_0^1 100 \sin(2\pi t) \, dt = \left[-\frac{100}{2\pi} \cos(2\pi t)\
'
End Sub


